"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const cliente_1 = __importDefault(require("../modelos/cliente"));
const endereco_1 = __importDefault(require("../modelos/endereco"));
const telefone_1 = __importDefault(require("../modelos/telefone"));
//Easter egg:Shiro melhor cachorro do mundo
let telefone1 = new telefone_1.default();
telefone1.ddd = '12';
telefone1.numero = '982518708';
let telefone2 = new telefone_1.default();
telefone2.ddd = '11';
telefone2.numero = '999999999';
let telefone3 = new telefone_1.default();
telefone3.ddd = '11';
telefone3.numero = '888888888';
let cliente = new cliente_1.default();
cliente.nome = `Pedro de Alcântara João Carlos Leopoldo Salvador`;
cliente.nomeSocial = `Dom Pedro II`;
cliente.dataCadastro = new Date(1840, 6, 23);
cliente.dataNascimento = new Date(1825, 11, 2);
cliente.telefones = [telefone1.clonar(), telefone2.clonar()];
let endereco = new endereco_1.default();
endereco.rua = `R. do Catete`;
endereco.bairro = `Copacabana`;
endereco.cidade = `Rio de Janeiro`;
endereco.estado = `Rio de Janeiro`;
endereco.pais = `Brasil`;
endereco.codigoPostal = `22220-000`;
cliente.endereco = endereco;
let dependente = new cliente_1.default();
dependente.nome = `Isabel Cristina Leopoldina Augusta Micaela`;
dependente.nomeSocial = `Princesa Isabel`;
dependente.dataCadastro = new Date(1921, 10, 14);
dependente.dataNascimento = new Date(1846, 6, 29);
dependente.endereco = cliente.endereco.clonar();
dependente.telefones = [telefone3.clonar()];
dependente.titular = cliente;
cliente.dependentes.push(dependente);
console.log(cliente);
console.log(dependente);
